language: python

python:
  - "2.7"
  - "3.3"

# command to install dependencies
install:
  - "pip install flake8"
  - "pip install nose"
  - "pip install codecov"

# command to run tests
script: ./run_tests.py

after_success:
  - codecov

cache:
  directories:
    - $HOME/.cache/pip  # Python packages from pip
